name: Deploy dist
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        # run: |
        #   echo "Cloning repo..."
        #   echo "${{toJson(github)}}"
        #   git clone https://github.com/${{github.repository}}.git
        uses: actions/checkout@v5

      - name: Install Node20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Build app
        run: npm run build
        env:
          VITE_MY_NAME: "SAMREEN MALIK"

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Get Code
  #       uses: actions/checkout@v5
  #     - name: Install Node 20
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 20
  #     - name: Install depencies
  #       run: npm ci
  #     - name: Build Project
  #       run: npm run build
  #     - name: Deploy
  #       run: echo "Deploy success"
